/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package HIRO;

import static HIRO.CHATBOT.answer;
import java.awt.event.*;
import java.util.*;



/**
 *
 * @author CREAM
 */
public class ABOUT extends javax.swing.JFrame {
public static String answer;
    /**
     * Creates new form PURPOSE
     */
    public ABOUT() {
        initComponents();
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnrealperson = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        screentext = new javax.swing.JTextArea();
        btnwhoareyou = new javax.swing.JButton();
        btnwhat = new javax.swing.JButton();
        btnback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnrealperson.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        btnrealperson.setText("<html> <body> <p align = center> Are you a</p><p align =center>real person?</p></body></html>");
        btnrealperson.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnrealperson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrealpersonActionPerformed(evt);
            }
        });
        jPanel1.add(btnrealperson, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, 140, 50));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        jLabel8.setText("About Hiro");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/baymaxball.gif"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 460, -1));

        screentext.setColumns(20);
        screentext.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        screentext.setRows(5);
        screentext.setText("HIRO:    Hi! What would you like to know?\n");
        screentext.setRequestFocusEnabled(false);
        jScrollPane2.setViewportView(screentext);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 440, 360));

        btnwhoareyou.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        btnwhoareyou.setText("Who are you?");
        btnwhoareyou.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnwhoareyou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnwhoareyouActionPerformed(evt);
            }
        });
        jPanel1.add(btnwhoareyou, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 140, 50));

        btnwhat.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        btnwhat.setText("<html> <body> <p align = center>What can you</p><p align =center>you offer?</p></body></html>");
        btnwhat.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnwhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnwhatActionPerformed(evt);
            }
        });
        jPanel1.add(btnwhat, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 450, 140, 50));

        btnback.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        btnback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/back.png"))); // NOI18N
        btnback.setBorder(null);
        btnback.setBorderPainted(false);
        btnback.setContentAreaFilled(false);
        btnback.setFocusPainted(false);
        btnback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnbackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnbackMouseExited(evt);
            }
        });
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        jPanel1.add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 50, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 785, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnrealpersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrealpersonActionPerformed
        screentext.append("YOU:     Are you a real person?\n");
        answer = "Real";
        whatDoIdo(answer);
    }//GEN-LAST:event_btnrealpersonActionPerformed

    private void btnwhoareyouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnwhoareyouActionPerformed
        screentext.append("YOU:     Who are you?\n");
        answer = "Explain";
        whatDoIdo(answer);
    }//GEN-LAST:event_btnwhoareyouActionPerformed

    private void btnwhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnwhatActionPerformed
        screentext.append("YOU:     What can you offer?\n");
        answer = "WhatElse";
        whatDoIdo(answer);
    }//GEN-LAST:event_btnwhatActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        new START().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnbackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbackMouseExited
        btnback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/back.png")));
    }//GEN-LAST:event_btnbackMouseExited

    private void btnbackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbackMouseEntered
        btnback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/backhover.png")));
    }//GEN-LAST:event_btnbackMouseEntered

    /**
     * @param args the command line arguments
     */
    
    public void whatDoIdo(String input){
        Map<String, String> questions = new HashMap<>();
        questions.put("Explain", "Hello, I'm Hiro! I'm delighted to be your \n"
                + "             personal healthcare assistant, here to provide\n"
                + "             you with information and assistance regarding\n"
                + "             various aspects of healthcare and hospital \n"
                + "             services. Whether you have inquiries about \n"
                + "             medical conditions, need help with tasks, \n"
                + "             or seek general information about our hospital \n"
                + "             facilities, I'm at your service.\n");
        questions.put("Real", "No, I'm not. It's important to remember that\n"
                + "             while I can offer valuable guidance and\n"
                + "             information, I cannot replace professional\n"
                + "             medical advice or  diagnosis. In the event of\n"
                + "             a medical emergency or if you require urgent\n"
                + "             assistance, please reach out to your nearest\n"
                + "             healthcare provider or contact emergency\n"
                + "             services immediately.\n"
                + "             Still, please don't hesitate to ask me \n"
                + "             anything you'd like to know, and I'll \n"
                + "             do my utmost to provide you with accurate\n"
                + "             and dependable information to support you\n"
                + "             on your healthcare journey.\n");
        questions.put("WhatElse", "I can offer a range of services and\n"
                + "             support to patients, and other people who\n"
                + "             need assistance.\n"
                + "             \n"
                + "             Here are some common features and \n"
                + "             benefits I give:\n"
                + "             \n"
                + "             1. Basic Information: I can provide general\n"
                + "                information about the hospital, such as\n"
                + "                its location, visiting hours, contact\n"
                + "`               details, and services offered.\n"
                + "                \n" 
                + "             2. Appointment Scheduling: Patients \n"
                + "                can use me to book appointments with\n"
                + "                doctors or other healthcare providers.\n"
                + "                \n" 
                + "             3. Key Facts: You can choose between\n"
                + "                three (3) common illnesses such as cough,\n"
                + "                fever and I will provide basic medical\n"
                + "                advice or recommend seeking immediate\n"
                + "                medical attention based on the severity\n"
                + "                of the symptoms.\n"
                + "                \n" 
                + "                It's important to note that my \n"
                + "                capabilities can vary depending on my\n"
                + "                design, integration with hospital systems,\n"
                + "                and the specific needs of the healthcare\n"
                + "                institution.\n");
        
        if (input.contains("Explain"))
              screentext.append("HIRO:     " + questions.get("Explain"));
        else if (input.contains("Real"))
              screentext.append("HIRO:     " + questions.get("Real"));
        else if (input.contains("WhatElse"))
              screentext.append("HIRO:     " + questions.get("WhatElse"));
    
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ABOUT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ABOUT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ABOUT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ABOUT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
            ABOUT purpose = new ABOUT();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                purpose.setVisible(true);
            }
        });
        
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnrealperson;
    private javax.swing.JButton btnwhat;
    private javax.swing.JButton btnwhoareyou;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private static javax.swing.JTextArea screentext;
    // End of variables declaration//GEN-END:variables
}
