/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HIRO;

import java.awt.*;
import java.util.*;
import java.io.*;
import javax.swing.JOptionPane;

/**
 *
 * @author julius
 */
public class APPOINTMENT extends javax.swing.JFrame {
    // INITIATE MAP STATIC PARA MA-CALL SIYA SA IBANG METHOD
    static Map <String,String> app = new LinkedHashMap<>();
    /**
     * Creates new form appointment
     */
    public APPOINTMENT() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lungRbtnGrp = new javax.swing.ButtonGroup();
        thyRbtnGrp = new javax.swing.ButtonGroup();
        kidRbtnGrp = new javax.swing.ButtonGroup();
        panelinput = new javax.swing.JPanel();
        txtlname = new javax.swing.JTextField();
        txtage = new javax.swing.JTextField();
        txtaddress = new javax.swing.JTextField();
        txtblood = new javax.swing.JTextField();
        txtcontact = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnsubmit = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        surgeryrbtnNO = new javax.swing.JRadioButton();
        asthmarbtnYES = new javax.swing.JRadioButton();
        asthmabtnNO = new javax.swing.JRadioButton();
        heartrbtnYES = new javax.swing.JRadioButton();
        heartbtnNO = new javax.swing.JRadioButton();
        surgerybtnYES = new javax.swing.JRadioButton();
        txtMed = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnback = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtfname = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtmi = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtgender = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtbdate = new javax.swing.JTextField();
        panelresult = new javax.swing.JPanel();
        scrollmsg = new javax.swing.JScrollPane();
        appform = new javax.swing.JTextArea();
        yesnopanel = new javax.swing.JPanel();
        btnyes = new javax.swing.JButton();
        btnno = new javax.swing.JButton();
        exitpanel = new javax.swing.JPanel();
        btnexit = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        scrollform = new javax.swing.JScrollPane();
        screentext = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        panelinput.setBackground(new java.awt.Color(255, 255, 255));
        panelinput.setLayout(null);

        txtlname.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        txtlname.setForeground(new java.awt.Color(153, 153, 153));
        txtlname.setText("Enter Last Name");
        txtlname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtlnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtlnameFocusLost(evt);
            }
        });
        txtlname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtlnameMouseEntered(evt);
            }
        });
        txtlname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlnameActionPerformed(evt);
            }
        });
        panelinput.add(txtlname);
        txtlname.setBounds(30, 140, 230, 40);

        txtage.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        txtage.setForeground(new java.awt.Color(153, 153, 153));
        txtage.setText("XX");
        txtage.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtageFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtageFocusLost(evt);
            }
        });
        txtage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtageActionPerformed(evt);
            }
        });
        panelinput.add(txtage);
        txtage.setBounds(230, 210, 70, 40);

        txtaddress.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        txtaddress.setForeground(new java.awt.Color(153, 153, 153));
        txtaddress.setText("Enter Address");
        txtaddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtaddressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtaddressFocusLost(evt);
            }
        });
        panelinput.add(txtaddress);
        txtaddress.setBounds(30, 280, 590, 40);

        txtblood.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        txtblood.setForeground(new java.awt.Color(153, 153, 153));
        txtblood.setText("Ex. A+");
        txtblood.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtbloodFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtbloodFocusLost(evt);
            }
        });
        txtblood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbloodActionPerformed(evt);
            }
        });
        panelinput.add(txtblood);
        txtblood.setBounds(470, 210, 150, 40);

        txtcontact.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        txtcontact.setForeground(new java.awt.Color(153, 153, 153));
        txtcontact.setText("Enter Contact Number");
        txtcontact.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtcontactFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtcontactFocusLost(evt);
            }
        });
        panelinput.add(txtcontact);
        txtcontact.setBounds(30, 350, 230, 40);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel1.setText("<html> <body><p align=center>Note: Please try to answer with correct information about you.</p>\n<p align= center>Type N/A if you do not know/remember your information detail. ");
        panelinput.add(jLabel1);
        jLabel1.setBounds(140, 60, 370, 40);

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel2.setText("M.I.");
        panelinput.add(jLabel2);
        jLabel2.setBounds(530, 110, 40, 40);

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel3.setText("Home Address:");
        panelinput.add(jLabel3);
        jLabel3.setBounds(40, 250, 120, 40);

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel4.setText("Blood Type:");
        panelinput.add(jLabel4);
        jLabel4.setBounds(480, 180, 110, 40);

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel5.setText("Contact Number:");
        panelinput.add(jLabel5);
        jLabel5.setBounds(40, 320, 121, 40);

        btnsubmit.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        btnsubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/btnsubmit.png"))); // NOI18N
        btnsubmit.setBorderPainted(false);
        btnsubmit.setContentAreaFilled(false);
        btnsubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnsubmitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnsubmitMouseExited(evt);
            }
        });
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });
        panelinput.add(btnsubmit);
        btnsubmit.setBounds(480, 590, 140, 60);

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel7.setText("E-mail Address:");
        panelinput.add(jLabel7);
        jLabel7.setBounds(290, 320, 130, 40);

        txtemail.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        txtemail.setForeground(new java.awt.Color(153, 153, 153));
        txtemail.setText("Enter E-mail Address");
        txtemail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtemailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtemailFocusLost(evt);
            }
        });
        panelinput.add(txtemail);
        txtemail.setBounds(280, 350, 340, 40);

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel8.setText("Do you have Asthma?");
        panelinput.add(jLabel8);
        jLabel8.setBounds(40, 400, 160, 40);

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel9.setText("Do you have any heart problems?");
        panelinput.add(jLabel9);
        jLabel9.setBounds(40, 440, 250, 40);

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel10.setText("<html><body> <p align=left>Have you had any surgeries  or operations</p><p align= left> in the past?</p></body><html>");
        jLabel10.setToolTipText("");
        panelinput.add(jLabel10);
        jLabel10.setBounds(40, 490, 320, 40);

        jLabel11.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel11.setText("Other medical history:");
        panelinput.add(jLabel11);
        jLabel11.setBounds(40, 540, 170, 40);

        kidRbtnGrp.add(surgeryrbtnNO);
        surgeryrbtnNO.setText("No");
        surgeryrbtnNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surgeryrbtnNOActionPerformed(evt);
            }
        });
        panelinput.add(surgeryrbtnNO);
        surgeryrbtnNO.setBounds(480, 500, 50, 20);

        lungRbtnGrp.add(asthmarbtnYES);
        asthmarbtnYES.setText("Yes");
        asthmarbtnYES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asthmarbtnYESActionPerformed(evt);
            }
        });
        panelinput.add(asthmarbtnYES);
        asthmarbtnYES.setBounds(380, 410, 70, 20);

        lungRbtnGrp.add(asthmabtnNO);
        asthmabtnNO.setText("No");
        asthmabtnNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asthmabtnNOActionPerformed(evt);
            }
        });
        panelinput.add(asthmabtnNO);
        asthmabtnNO.setBounds(480, 410, 50, 20);

        thyRbtnGrp.add(heartrbtnYES);
        heartrbtnYES.setText("Yes");
        heartrbtnYES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heartrbtnYESActionPerformed(evt);
            }
        });
        panelinput.add(heartrbtnYES);
        heartrbtnYES.setBounds(380, 450, 70, 20);

        thyRbtnGrp.add(heartbtnNO);
        heartbtnNO.setText("No");
        heartbtnNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heartbtnNOActionPerformed(evt);
            }
        });
        panelinput.add(heartbtnNO);
        heartbtnNO.setBounds(480, 450, 50, 20);

        kidRbtnGrp.add(surgerybtnYES);
        surgerybtnYES.setText("Yes");
        surgerybtnYES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surgerybtnYESActionPerformed(evt);
            }
        });
        panelinput.add(surgerybtnYES);
        surgerybtnYES.setBounds(380, 500, 60, 20);

        txtMed.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        txtMed.setForeground(new java.awt.Color(153, 153, 153));
        txtMed.setText("Enter Medical History");
        txtMed.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMedFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMedFocusLost(evt);
            }
        });
        txtMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedActionPerformed(evt);
            }
        });
        panelinput.add(txtMed);
        txtMed.setBounds(220, 540, 380, 40);

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel6.setText("First Name: ");
        panelinput.add(jLabel6);
        jLabel6.setBounds(280, 110, 100, 40);

        jLabel12.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        jLabel12.setText("SET AN APPOINTMENT");
        panelinput.add(jLabel12);
        jLabel12.setBounds(160, 20, 340, 40);

        btnback.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        btnback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/back.png"))); // NOI18N
        btnback.setBorder(null);
        btnback.setBorderPainted(false);
        btnback.setContentAreaFilled(false);
        btnback.setFocusPainted(false);
        btnback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnbackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnbackMouseExited(evt);
            }
        });
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        panelinput.add(btnback);
        btnback.setBounds(590, 10, 45, 41);

        jLabel13.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel13.setText("Last Name : ");
        panelinput.add(jLabel13);
        jLabel13.setBounds(40, 110, 100, 40);

        txtfname.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        txtfname.setForeground(new java.awt.Color(153, 153, 153));
        txtfname.setText("Enter First Name");
        txtfname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtfnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtfnameFocusLost(evt);
            }
        });
        txtfname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtfnameMouseEntered(evt);
            }
        });
        txtfname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfnameActionPerformed(evt);
            }
        });
        panelinput.add(txtfname);
        txtfname.setBounds(270, 140, 250, 40);

        jLabel14.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel14.setText("Birthdate:");
        panelinput.add(jLabel14);
        jLabel14.setBounds(40, 180, 70, 40);

        txtmi.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        txtmi.setForeground(new java.awt.Color(153, 153, 153));
        txtmi.setText("Enter M.I.");
        txtmi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtmiFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtmiFocusLost(evt);
            }
        });
        txtmi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmiActionPerformed(evt);
            }
        });
        panelinput.add(txtmi);
        txtmi.setBounds(530, 140, 90, 40);

        jLabel15.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel15.setText("Gender:");
        panelinput.add(jLabel15);
        jLabel15.setBounds(330, 180, 110, 40);

        txtgender.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        txtgender.setForeground(new java.awt.Color(153, 153, 153));
        txtgender.setText("Male/Female");
        txtgender.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtgenderFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtgenderFocusLost(evt);
            }
        });
        txtgender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgenderActionPerformed(evt);
            }
        });
        panelinput.add(txtgender);
        txtgender.setBounds(320, 210, 130, 40);

        jLabel16.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel16.setText(" Age:");
        panelinput.add(jLabel16);
        jLabel16.setBounds(230, 180, 70, 40);

        txtbdate.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        txtbdate.setForeground(new java.awt.Color(153, 153, 153));
        txtbdate.setText("MM/DD/YYYY");
        txtbdate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtbdateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtbdateFocusLost(evt);
            }
        });
        txtbdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbdateActionPerformed(evt);
            }
        });
        panelinput.add(txtbdate);
        txtbdate.setBounds(30, 210, 160, 40);

        panelresult.setBackground(new java.awt.Color(255, 255, 255));
        panelresult.setLayout(null);

        appform.setColumns(20);
        appform.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        appform.setRows(5);
        appform.setFocusable(false);
        appform.setRequestFocusEnabled(false);
        scrollmsg.setViewportView(appform);

        panelresult.add(scrollmsg);
        scrollmsg.setBounds(40, 60, 560, 340);

        yesnopanel.setBackground(new java.awt.Color(255, 255, 255));

        btnyes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/btnyes.png"))); // NOI18N
        btnyes.setBorder(null);
        btnyes.setBorderPainted(false);
        btnyes.setContentAreaFilled(false);
        btnyes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnyesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnyesMouseExited(evt);
            }
        });
        btnyes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnyesActionPerformed(evt);
            }
        });

        btnno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/btnno.png"))); // NOI18N
        btnno.setBorder(null);
        btnno.setBorderPainted(false);
        btnno.setContentAreaFilled(false);
        btnno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnnoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnnoMouseExited(evt);
            }
        });
        btnno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout yesnopanelLayout = new javax.swing.GroupLayout(yesnopanel);
        yesnopanel.setLayout(yesnopanelLayout);
        yesnopanelLayout.setHorizontalGroup(
            yesnopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(yesnopanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnyes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(btnno)
                .addContainerGap())
        );
        yesnopanelLayout.setVerticalGroup(
            yesnopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(yesnopanelLayout.createSequentialGroup()
                .addGroup(yesnopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnyes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnno, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        panelresult.add(yesnopanel);
        yesnopanel.setBounds(180, 540, 300, 60);

        exitpanel.setBackground(new java.awt.Color(255, 255, 255));
        exitpanel.setLayout(null);

        btnexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/btnexit.png"))); // NOI18N
        btnexit.setBorder(null);
        btnexit.setBorderPainted(false);
        btnexit.setContentAreaFilled(false);
        btnexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnexitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnexitMouseExited(evt);
            }
        });
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });
        exitpanel.add(btnexit);
        btnexit.setBounds(10, 10, 100, 47);

        btnsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/btnsave.png"))); // NOI18N
        btnsave.setBorder(null);
        btnsave.setBorderPainted(false);
        btnsave.setContentAreaFilled(false);
        btnsave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnsaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnsaveMouseExited(evt);
            }
        });
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        exitpanel.add(btnsave);
        btnsave.setBounds(190, 10, 100, 47);

        panelresult.add(exitpanel);
        exitpanel.setBounds(180, 540, 300, 60);

        jLabel17.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        jLabel17.setText("APPOINTMENT FORM");
        panelresult.add(jLabel17);
        jLabel17.setBounds(170, 20, 340, 40);

        screentext.setColumns(20);
        screentext.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        screentext.setRows(5);
        screentext.setFocusable(false);
        screentext.setRequestFocusEnabled(false);
        scrollform.setViewportView(screentext);

        panelresult.add(scrollform);
        scrollform.setBounds(40, 410, 560, 120);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelinput, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(panelresult, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 3, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelinput, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelresult, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtlnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlnameActionPerformed

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
        String lname = txtlname.getText();
        String fname = txtfname.getText();
        String mi = txtmi.getText();
        String bdate = txtbdate.getText();
        String age = txtage.getText();
        String gen = txtgender.getText();
        String blood = txtblood.getText();
        String address = txtaddress.getText();
        String contact = txtcontact.getText();
        String email = txtemail.getText();
        String medical  = txtMed.getText();
        // GETTING TEXT FROM JTEXTFIELD TO STRING - STRING INSERTED INTO VALUES FOR EACH KEY
          app.put("Last Name", lname);
          app.put("First Name", fname);
          app.put("Middle Initial", mi);
          app.put("Birthdate", bdate);
          app.put("Age", age + " years old");
          app.put("Gender", gen);
          app.put("Blood Type" , blood);
          app.put("Home Address", address);
          app.put("Contact Number", contact);
          app.put("Email Address" , email);
        //RADIOBUTTONS IF YES/NO - ALSO INSERTED INTO VALUES
        if(asthmarbtnYES.isSelected())
            app.put("Asthma" ,"Yes" );
         
        else if(asthmabtnNO.isSelected())
            app.put("Asthma", "No");
          
        if(heartrbtnYES.isSelected())
            app.put("Heart Problem" ,"Yes" );
        
        else if(heartbtnNO.isSelected())
            app.put("Heart Problem", "No"); 
        
        if(surgerybtnYES.isSelected())
            app.put("Past Surgeries" ,"Yes" );
         
        else if(surgeryrbtnNO.isSelected())
            app.put("Past Surgeries", "No");
          
            app.put("Past Medical History", medical);
        //USING ITERATION PARA MADISPLAY LAHAT NG LAMAN NG MAP SA TEXT AREA.
        for (Map.Entry a : app.entrySet() ){
            appform.append((String) a.getKey() +": "+ a.getValue() + "\n");
        }
          
        screentext.append("HIRO:    Are the information above correct? \n");
        panelinput.setVisible(false);
        exitpanel.setVisible(false);
        panelresult.setVisible(true);
        yesnopanel.setVisible(true);
        
    }//GEN-LAST:event_btnsubmitActionPerformed

    private void txtlnameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtlnameMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlnameMouseEntered

    private void txtlnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtlnameFocusGained
        if (txtlname.getText().equals("Enter Last Name")){
            txtlname.setText("");
        }
        txtlname.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtlnameFocusGained

    private void txtlnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtlnameFocusLost
        if (txtlname.getText().equals("")){
            txtlname.setText("Enter Last Name");
        }
        
        txtlname.setForeground(new Color(153, 153, 153));
    }//GEN-LAST:event_txtlnameFocusLost

    private void btnyesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnyesActionPerformed
        
        screentext.append("YOU:    Yes.\n");
        screentext.append("HIRO:    Our personnel will contact you within the day.\n"
                + "             To save your form, click save. Thank you!\n");  
        exitpanel.setVisible(true);
        yesnopanel.setVisible(false);
        // AFTER CONFIRMING CORRECT INFORMATION - CLEAR THE MAP FOR NEW USER APPOINTMENT
        app.clear();
    }//GEN-LAST:event_btnyesActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        //
        app.clear();
        new INTRODUCTION().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnexitActionPerformed

    private void btnnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnoActionPerformed
        // PAG NAG ANSER NG NO SI USER - BALIK SIYA SA EDITING NG APPLICATION FORM, CLEAR MAP, CLEAR TEXT.
        app.clear();
        panelresult.setVisible(false);
        appform.setText("");
        screentext.setText("");
        panelinput.setVisible(true);
    }//GEN-LAST:event_btnnoActionPerformed

    private void txtbloodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbloodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbloodActionPerformed

    private void txtageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtageActionPerformed

    private void surgeryrbtnNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surgeryrbtnNOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_surgeryrbtnNOActionPerformed

    private void asthmarbtnYESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asthmarbtnYESActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_asthmarbtnYESActionPerformed

    private void asthmabtnNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asthmabtnNOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_asthmabtnNOActionPerformed

    private void heartrbtnYESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heartrbtnYESActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_heartrbtnYESActionPerformed

    private void heartbtnNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heartbtnNOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_heartbtnNOActionPerformed

    private void surgerybtnYESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surgerybtnYESActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_surgerybtnYESActionPerformed

    private void txtMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedActionPerformed

    private void txtageFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtageFocusGained
        if (txtage.getText().equals("XX")){
            txtage.setText("");
        }
        txtage.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_txtageFocusGained

    private void txtageFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtageFocusLost
          if (txtage.getText().equals("")){
            txtage.setText("XX");
        }
        txtage.setForeground(new Color(153, 153, 153));
    }//GEN-LAST:event_txtageFocusLost

    private void txtaddressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtaddressFocusGained
       if (txtaddress.getText().equals("Enter Address")){
           txtaddress.setText("");
        }
        txtaddress.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_txtaddressFocusGained

    private void txtaddressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtaddressFocusLost
  if (txtaddress.getText().equals("")){
       txtaddress.setText("Enter Address");
        }
        txtaddress.setForeground(new Color(153, 153, 153));
    }//GEN-LAST:event_txtaddressFocusLost

    private void txtbloodFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtbloodFocusGained
   if (txtblood.getText().equals("Ex. A+")){
           txtblood.setText("");
        }
        txtblood.setForeground(new Color(0, 0, 0));
        
    }//GEN-LAST:event_txtbloodFocusGained

    private void txtbloodFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtbloodFocusLost
if (txtblood.getText().equals("")){
       txtblood.setText("Ex. A+");
        }
        txtblood.setForeground(new Color(153, 153, 153));

    }//GEN-LAST:event_txtbloodFocusLost

    private void txtcontactFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcontactFocusGained
        if (txtcontact.getText().equals("Enter Contact Number")){
           txtcontact.setText("");
        }
        txtcontact.setForeground(new Color(0, 0, 0));

    }//GEN-LAST:event_txtcontactFocusGained

    private void txtcontactFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcontactFocusLost
       if (txtcontact.getText().equals("")){
       txtcontact.setText("Enter Contact Number");
        }
        txtcontact.setForeground(new Color(153, 153, 153));
    }//GEN-LAST:event_txtcontactFocusLost

    private void txtemailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtemailFocusGained
        if (txtemail.getText().equals("Enter E-mail Address")){
           txtemail.setText("");
        }
        txtemail.setForeground(new Color(0, 0, 0));
        
   
    }//GEN-LAST:event_txtemailFocusGained

    private void txtemailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtemailFocusLost
       if (txtemail.getText().equals("")){
       txtemail.setText("Enter E-mail Address");
        }
        txtemail.setForeground(new Color(153, 153, 153)); 

    }//GEN-LAST:event_txtemailFocusLost

    private void txtMedFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMedFocusGained
             if (txtMed.getText().equals("Enter Medical History")){
           txtMed.setText("");
        }
        txtMed.setForeground(new Color(0, 0, 0)); 

    }//GEN-LAST:event_txtMedFocusGained

    private void txtMedFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMedFocusLost
          if (txtMed.getText().equals("")){
       txtMed.setText("Enter Medical History");
        }
        txtMed.setForeground(new Color(153, 153, 153));                                  

    }//GEN-LAST:event_txtMedFocusLost

    private void btnbackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbackMouseEntered
        btnback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/backhover.png")));
    }//GEN-LAST:event_btnbackMouseEntered

    private void btnbackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbackMouseExited
        btnback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/back.png")));
    }//GEN-LAST:event_btnbackMouseExited

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        CHATBOT chatbot = new CHATBOT();
        this.dispose();
        chatbot.panelfever.setVisible(false);
        chatbot.panelsickness.setVisible(false);
        chatbot.panelcoughs.setVisible(false);
        chatbot.paneldoctortype.setVisible(false);
        chatbot.setVisible(true);
    }//GEN-LAST:event_btnbackActionPerformed

    private void txtfnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfnameFocusGained
        if (txtfname.getText().equals("Enter First Name")){
           txtfname.setText("");
        }
        txtfname.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_txtfnameFocusGained

    private void txtfnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfnameFocusLost
        if (txtfname.getText().equals("")){
       txtfname.setText("Enter First Name");
        }
        txtfname.setForeground(new Color(153, 153, 153)); 
    }//GEN-LAST:event_txtfnameFocusLost

    private void txtfnameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtfnameMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfnameMouseEntered

    private void txtfnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfnameActionPerformed

    private void txtmiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtmiFocusGained
        if (txtmi.getText().equals("Enter M.I.")){
           txtmi.setText("");
        }
        txtmi.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_txtmiFocusGained

    private void txtmiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtmiFocusLost
        if (txtmi.getText().equals("")){
       txtmi.setText("Enter M.I.");
        }
        txtmi.setForeground(new Color(153, 153, 153)); 
    }//GEN-LAST:event_txtmiFocusLost

    private void txtmiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmiActionPerformed

    private void txtgenderFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtgenderFocusGained
        if (txtgender.getText().equals("Male/Female")){
           txtgender.setText("");
        }
        txtgender.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_txtgenderFocusGained

    private void txtgenderFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtgenderFocusLost
        if (txtgender.getText().equals("")){
       txtgender.setText("Male/Female");
        }
        txtgender.setForeground(new Color(153, 153, 153)); 
    }//GEN-LAST:event_txtgenderFocusLost

    private void txtgenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgenderActionPerformed

    private void txtbdateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtbdateFocusGained
        if (txtbdate.getText().equals("MM/DD/YYYY")){
           txtbdate.setText("");
        }
        txtbdate.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_txtbdateFocusGained

    private void txtbdateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtbdateFocusLost
        if (txtbdate.getText().equals("")){
       txtbdate.setText("MM/DD/YYYY");
        }
        txtbdate.setForeground(new Color(153, 153, 153)); 
    }//GEN-LAST:event_txtbdateFocusLost

    private void txtbdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbdateActionPerformed

    private void btnsubmitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsubmitMouseEntered
        btnsubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/btnsubmithov.png")));
    }//GEN-LAST:event_btnsubmitMouseEntered

    private void btnsubmitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsubmitMouseExited
        btnsubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/btnsubmit.png")));
    }//GEN-LAST:event_btnsubmitMouseExited

    private void btnyesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnyesMouseEntered
        btnyes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/btnyeshov.png")));
    }//GEN-LAST:event_btnyesMouseEntered

    private void btnyesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnyesMouseExited
        btnyes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/btnyes.png")));
    }//GEN-LAST:event_btnyesMouseExited

    private void btnnoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnnoMouseEntered
        btnno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/btnnohov.png")));
    }//GEN-LAST:event_btnnoMouseEntered

    private void btnnoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnnoMouseExited
        btnno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/btnno.png")));
    }//GEN-LAST:event_btnnoMouseExited

    private void btnexitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnexitMouseEntered
        btnexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/btnexithov.png")));
    }//GEN-LAST:event_btnexitMouseEntered

    private void btnexitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnexitMouseExited
        btnexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/btnexit.png")));
    }//GEN-LAST:event_btnexitMouseExited

    private void btnsaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsaveMouseEntered
        btnsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/btnsavehov.png")));
    }//GEN-LAST:event_btnsaveMouseEntered

    private void btnsaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsaveMouseExited
        btnsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/btnsave.png")));
    }//GEN-LAST:event_btnsaveMouseExited

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        /*NAGINITIATE NG STRING PARA MAKUHA UNG VALUES NG FULL NAME
        GUMAMIT NG TRY AND CATCH PARA CHECK LANG UNG ERROR
        BUFFEREDWRITER PARA MA-SAVE SA FOLDER UNG TXT FILE NG APPOINTMENT FORM NI USER*/
        String l= txtlname.getText();
        String f = txtfname.getText();
        String m = txtmi.getText();
        try
        {
           BufferedWriter writer = new BufferedWriter(new FileWriter(l +", " + f +" "+ m + ".txt"));
            writer.append(appform.getText());
            writer.close();
            JOptionPane.showMessageDialog(null,"Appointment Form Saved", "Saved", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            new START().setVisible(true);
        }
           
        catch (IOException except)
        {
            except.printStackTrace();
        }
    }//GEN-LAST:event_btnsaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(APPOINTMENT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(APPOINTMENT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(APPOINTMENT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(APPOINTMENT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
            
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new APPOINTMENT().setVisible(true);
                panelresult.setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextArea appform;
    private javax.swing.JRadioButton asthmabtnNO;
    private javax.swing.JRadioButton asthmarbtnYES;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnno;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnsubmit;
    private javax.swing.JButton btnyes;
    public static javax.swing.JPanel exitpanel;
    private javax.swing.JRadioButton heartbtnNO;
    private javax.swing.JRadioButton heartrbtnYES;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.ButtonGroup kidRbtnGrp;
    private javax.swing.ButtonGroup lungRbtnGrp;
    private javax.swing.JPanel panelinput;
    private static javax.swing.JPanel panelresult;
    public static javax.swing.JTextArea screentext;
    private javax.swing.JScrollPane scrollform;
    private javax.swing.JScrollPane scrollmsg;
    private javax.swing.JRadioButton surgerybtnYES;
    private javax.swing.JRadioButton surgeryrbtnNO;
    private javax.swing.ButtonGroup thyRbtnGrp;
    private javax.swing.JTextField txtMed;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtbdate;
    private javax.swing.JTextField txtblood;
    private static javax.swing.JTextField txtcontact;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtgender;
    private javax.swing.JTextField txtlname;
    private javax.swing.JTextField txtmi;
    public static javax.swing.JPanel yesnopanel;
    // End of variables declaration//GEN-END:variables
}
