/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HIRO;

/**
 *
 * @author julius
 */
public class START extends javax.swing.JFrame {

    /**
     * Creates new form PURPROSE
     */
    public START() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btndo = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnass = new javax.swing.JButton();
        btngoback = new javax.swing.JButton();
        btnback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/baymax.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(380, 40, 353, 436);

        btndo.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N
        btndo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/btndo.png"))); // NOI18N
        btndo.setBorder(null);
        btndo.setBorderPainted(false);
        btndo.setContentAreaFilled(false);
        btndo.setFocusPainted(false);
        btndo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btndoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btndoMouseExited(evt);
            }
        });
        btndo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndoActionPerformed(evt);
            }
        });
        jPanel1.add(btndo);
        btndo.setBounds(90, 210, 252, 67);

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        jLabel7.setText("help you with?");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(110, 130, 206, 40);

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        jLabel8.setText("What can I");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(130, 80, 160, 40);

        btnass.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N
        btnass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/btnass.png"))); // NOI18N
        btnass.setBorder(null);
        btnass.setBorderPainted(false);
        btnass.setContentAreaFilled(false);
        btnass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnassMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnassMouseExited(evt);
            }
        });
        btnass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnassActionPerformed(evt);
            }
        });
        jPanel1.add(btnass);
        btnass.setBounds(90, 290, 252, 67);

        btngoback.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N
        btngoback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/btnnvm.png"))); // NOI18N
        btngoback.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btngoback.setBorderPainted(false);
        btngoback.setContentAreaFilled(false);
        btngoback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btngobackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btngobackMouseExited(evt);
            }
        });
        btngoback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngobackActionPerformed(evt);
            }
        });
        jPanel1.add(btngoback);
        btngoback.setBounds(90, 370, 252, 67);

        btnback.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        btnback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/back.png"))); // NOI18N
        btnback.setBorder(null);
        btnback.setBorderPainted(false);
        btnback.setContentAreaFilled(false);
        btnback.setFocusPainted(false);
        btnback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnbackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnbackMouseExited(evt);
            }
        });
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        jPanel1.add(btnback);
        btnback.setBounds(730, 10, 45, 41);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 781, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndoActionPerformed
        this.dispose();
        new ABOUT().setVisible(true);
    }//GEN-LAST:event_btndoActionPerformed

    private void btnassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnassActionPerformed
        CHATBOT chatbot = new CHATBOT();
        this.dispose();
        chatbot.panelfever.setVisible(false);
        chatbot.panelsickness.setVisible(false);
        chatbot.panelcoughs.setVisible(false);
        chatbot.paneldoctortype.setVisible(false);
        chatbot.setVisible(true);
        
        
    }//GEN-LAST:event_btnassActionPerformed

    private void btngobackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngobackActionPerformed
        this.dispose();
        new INTRODUCTION().setVisible(true);
    }//GEN-LAST:event_btngobackActionPerformed

    private void btnbackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbackMouseEntered
        btnback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/backhover.png")));
    }//GEN-LAST:event_btnbackMouseEntered

    private void btnbackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbackMouseExited
        btnback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/back.png")));
    }//GEN-LAST:event_btnbackMouseExited

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        this.dispose();
        new INTRODUCTION().setVisible(true);
    }//GEN-LAST:event_btnbackActionPerformed

    private void btndoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndoMouseEntered
       btndo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/btndohov.png")));
    }//GEN-LAST:event_btndoMouseEntered

    private void btndoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndoMouseExited
        btndo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/btndo.png")));
    }//GEN-LAST:event_btndoMouseExited

    private void btnassMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnassMouseEntered
        btnass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/btnasshov.png")));
    }//GEN-LAST:event_btnassMouseEntered

    private void btnassMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnassMouseExited
        btnass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/btnass.png")));
    }//GEN-LAST:event_btnassMouseExited

    private void btngobackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btngobackMouseEntered
        btngoback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/btnnvmhov.png")));
    }//GEN-LAST:event_btngobackMouseEntered

    private void btngobackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btngobackMouseExited
        btngoback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/btnnvm.png")));
    }//GEN-LAST:event_btngobackMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(START.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(START.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(START.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(START.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new START().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnass;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btndo;
    private javax.swing.JButton btngoback;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
